// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzfzrailvyqllwwuppza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZnpyYWlsdnlxbGx3d3VwcHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjY1NzMsImV4cCI6MjA2MjA0MjU3M30.cVvE68CXLDuOsYUpbypt7v2gIax7XxrKMUrKRYNCn6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);